services:
  docker_state_exporter:
    container_name: docker_state_exporter
    image: docker_state_exporter
    user: root
    read_only: true
    security_opt:
      - no-new-privileges:true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ="Europe/Kyiv"
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "9110:8080/tcp"
    restart: unless-stopped
    healthcheck:
      test: wget -q -O - localhost:8080/metrics | grep -q "container_restartcount"
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s
