services:
  docker_state_exporter:
    container_name: docker_state_exporter
    image: docker_state_exporter
    environment:
      - TZ="Europe/Kyiv"
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    ports:
      - "9110:8080/tcp"
    restart: unless-stopped
    healthcheck:
      test: wget -q -O - localhost:8080/metrics | grep -q "container_restartcount"
      interval: 120s
      timeout: 5s
      retries: 2
